name: Builds

on: [push, pull_request]

jobs:
  electron-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Package
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-linux-artifact
          path: dist/*.deb

  electron-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Package
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-windows-artifact
          path: dist/*Setup*.exe

  electron-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Package
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-macos-artifact
          path: dist/*.dmg
